from typing import Dict, Any, List
from core.ollama import OllamaManager
from core.db import DatabaseStore
from core.decomposer import TaskDecomposer
from core.distiller import RuleDistiller
from core.planner import ExecutionPlanner
from core.critic import ExecutionCritic
from core.memory import VectorMemoryStore


class AdminAdvisor:
    def __init__(self):
        self.ollama = OllamaManager()
        self.db = DatabaseStore()
        self.decomposer = TaskDecomposer(self.ollama)
        self.distiller = RuleDistiller(self.ollama)
        self.planner = ExecutionPlanner(self.ollama)
        self.critic = ExecutionCritic(self.ollama, self.db)
        self.memory = VectorMemoryStore(ollama=self.ollama)

    def analyze_and_plan(self, user_goal: str) -> Dict[str, Any]:
        profile_facts = self.db.get_system_profile()
        stored_rules = [f"[{r['context_key']}]: {r['description']}" for r in self.db.get_system_rules()]

        # Retrieve semantically similar execution history from Vector Memory
        historical_memories = self.memory.query_similar_memories(user_goal, n_results=3)

        decomposition = self.decomposer.decompose_goal(user_goal)
        distilled_directives = self.distiller.distill_rules(
            phase_objective=user_goal,
            historical_rules=stored_rules
        )

        plan = self.planner.generate_plan(
            goal=user_goal,
            profile_facts=profile_facts,
            distilled_rules=distilled_directives,
            historical_memories=historical_memories
        )

        action_commands = [
            step["command"] for step in plan.get("steps", [])
            if step.get("type") == "action" or "command" in step
        ]

        script_code = "#!/usr/bin/env bash\nset -euo pipefail\n\n"
        script_code += f"# Generated by SysAgent for: {user_goal}\n\n"
        for cmd in action_commands:
            script_code += f"{cmd}\n"

        return {
            "decomposition": decomposition,
            "distilled_rules": distilled_directives,
            "historical_memories": historical_memories,
            "plan": plan,
            "generated_script": script_code
        }

    def record_successful_execution(self, goal: str, plan_summary: str, output: str):
        """
        Persists completed tasks to ChromaDB vector store.
        """
        self.memory.add_memory(
            goal=goal,
            plan_summary=plan_summary,
            result_output=output,
            status="success"
        )

    def diagnose_execution_failure(self, command: str, error_output: str, exit_code: int = 1) -> Dict[str, Any]:
        return self.critic.analyze_failure(command, error_output, exit_code)